
echo off
echo --------------------------------
echo %DATE%  %TIME%
echo ________________________________
echo .
echo ..
echo ...
echo ....
echo Copying Files from Jekyll playpen to git location ....
echo ....
echo ...
echo ..
echo .
echo --------------------------------
echo Copying Help Center Doc (3 dirs)....
echo ________________________________
echo ....
echo ....
C:
cd \Users\grraka\mysite
echo ....
echo ....
copy  \Users\grraka\mysite\*.* U:\github\gregraka.github.io
echo ....
echo ....
cd _site
echo ....
echo ....
copy  *.* U:\github\gregraka.github.io\_site
echo ....
echo ....
cd assets
echo ....
echo ....
copy  *.* U:\github\gregraka.github.io\_site\assets
echo ....
echo ....
cd ..\about
echo ....
echo ....
copy  *.* U:\github\gregraka.github.io\_site\about
echo ....
echo ....
echo --------------------------------
echo %DATE%  %TIME%
echo ________________________________
pause
